import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const themesDir = path.join(__dirname, '..', 'themes');

const palettes = {
  light: {
    name: 'Nebula Aura Light',
    type: 'light',
    bg: '#F2F1F8',
    fg: '#2E2D3A',
    selection: '#D4D0EA',
    comment: '#7E7899',
    cyan: '#2D9CDB',
    green: '#3D9A6E',
    orange: '#C07840',
    pink: '#9B59B6',
    purple: '#6B5BD4',
    red: '#C04A5A',
    yellow: '#9A8A2E',
    lineHighlight: '#E8E6F2',
    bgLight: '#EAE8F3',
    bgLighter: '#F7F6FB',
    bgDark: '#E2E0ED',
    bgDarker: '#D8D5E6',
    nonText: '#2E2D3A18',
    tabDrop: '#6B5BD430',
    tempQuotes: '#9A8A2E',
    tempPropertyQuotes: '#6B5BD4',
    cursor: '#6B5BD4',
    semanticHighlighting: true,
    ansi: [
      '#E2E0ED', '#C04A5A', '#3D9A6E', '#9A8A2E', '#4A6FA5', '#6B5BD4',
      '#2D9CDB', '#2E2D3A', '#9A96B0', '#D04A62', '#4AAF78', '#B09A38',
      '#5A82B8', '#7B6BE0', '#38A8D8', '#F7F6FB',
    ],
  },
  dark: {
    name: 'Nebula Aura Dark',
    type: 'dark',
    bg: '#1A1B26',
    fg: '#D5D8E8',
    selection: '#3A3F5C',
    comment: '#6B7094',
    cyan: '#6CB4EE',
    green: '#7FD99A',
    orange: '#E8A86A',
    pink: '#D48CB8',
    purple: '#8B9FD4',
    red: '#E06A7A',
    yellow: '#D4C878',
    lineHighlight: '#222433',
    bgLight: '#222433',
    bgLighter: '#2A2D42',
    bgDark: '#151621',
    bgDarker: '#12131C',
    nonText: '#D5D8E818',
    tabDrop: '#3A3F5C70',
    tempQuotes: '#D4C878',
    tempPropertyQuotes: '#6CB4EE',
    cursor: '#6CB4EE',
    semanticHighlighting: true,
    ansi: [
      '#151621', '#E06A7A', '#7FD99A', '#D4C878', '#6CB4EE', '#8B9FD4',
      '#7EC8E8', '#D5D8E8', '#6B7094', '#F07888', '#8FE8AA', '#E4D888',
      '#7CC4F8', '#9BAFE4', '#9EDCF0', '#F0F2FA',
    ],
  },
  violet: {
    name: 'Nebula Aura Violet',
    type: 'dark',
    bg: '#171320',
    fg: '#E8E4F0',
    selection: '#3D3558',
    comment: '#6E5F96',
    cyan: '#67CFE9',
    green: '#6EE7A8',
    orange: '#E8A574',
    pink: '#E06BAA',
    purple: '#A78BFA',
    red: '#F07188',
    yellow: '#E8DC78',
    lineHighlight: '#231E35',
    bgLight: '#1F1A2E',
    bgLighter: '#2A2440',
    bgDark: '#12101C',
    bgDarker: '#0E0C16',
    nonText: '#E8E4F018',
    tabDrop: '#3D355870',
    tempQuotes: '#E8DC78',
    tempPropertyQuotes: '#A78BFA',
    cursor: '#E06BAA',
    ansi: [
      '#12101C', '#E06BAA', '#6EE7A8', '#E8DC78', '#67CFE9', '#A78BFA',
      '#8AE8DC', '#E8E4F0', '#7A6E98', '#F07898', '#7EF8B8', '#F0E888',
      '#78D8F8', '#B89BFA', '#A8FFFF', '#F8F6FC',
    ],
    semanticHighlighting: true,
  },
  midnight: {
    name: 'Nebula Aura Midnight',
    type: 'dark',
    bg: '#0B1020',
    fg: '#DDE7F3',
    selection: '#253457',
    comment: '#64748B',
    cyan: '#22D3EE',
    green: '#6EE7B7',
    orange: '#FBBF24',
    pink: '#C084FC',
    purple: '#7C8CFF',
    red: '#F87171',
    yellow: '#A7F3D0',
    lineHighlight: '#0E1528',
    bgLight: '#070B16',
    bgLighter: '#121A30',
    bgDark: '#080D1A',
    bgDarker: '#050810',
    nonText: '#DDE7F318',
    tabDrop: '#25345770',
    tempQuotes: '#A7F3D0',
    tempPropertyQuotes: '#7C8CFF',
    cursor: '#22D3EE',
    semanticHighlighting: true,
    ansi: [
      '#050810', '#F87171', '#6EE7B7', '#A7F3D0', '#7C8CFF', '#C084FC',
      '#22D3EE', '#DDE7F3', '#64748B', '#FB7185', '#86EFAC', '#FDE68A',
      '#93A8FF', '#D8B4FE', '#67E8F9', '#F0F6FC',
    ],
  },
};

function alpha(hex, opacity) {
  const value = Math.round(opacity * 255)
    .toString(16)
    .padStart(2, '0');
  return `${hex}${value}`;
}

function buildColors(p) {
  const [c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15] = p.ansi;

  return {
    'terminal.background': p.bg,
    'terminal.foreground': p.fg,
    'terminal.ansiBlack': c0,
    'terminal.ansiRed': c1,
    'terminal.ansiGreen': c2,
    'terminal.ansiYellow': c3,
    'terminal.ansiBlue': c4,
    'terminal.ansiMagenta': c5,
    'terminal.ansiCyan': c6,
    'terminal.ansiWhite': c7,
    'terminal.ansiBrightBlack': c8,
    'terminal.ansiBrightRed': c9,
    'terminal.ansiBrightGreen': c10,
    'terminal.ansiBrightYellow': c11,
    'terminal.ansiBrightBlue': c12,
    'terminal.ansiBrightMagenta': c13,
    'terminal.ansiBrightCyan': c14,
    'terminal.ansiBrightWhite': c15,
    'terminal.selectionBackground': alpha(p.comment, 0.45),
    'terminalCursor.background': c0,
    'terminalCursor.foreground': p.fg,
    contrastBorder: p.bgDarker,
    focusBorder: p.comment,
    foreground: p.fg,
    'selection.background': p.purple,
    errorForeground: p.red,
    'button.background': p.selection,
    'button.foreground': p.fg,
    'dropdown.background': p.bgLight,
    'dropdown.border': p.bgDarker,
    'dropdown.foreground': p.fg,
    'input.background': p.bg,
    'input.foreground': p.fg,
    'input.border': p.bgDarker,
    'input.placeholderForeground': p.comment,
    'inputOption.activeBorder': p.purple,
    'inputValidation.infoBorder': p.pink,
    'inputValidation.warningBorder': p.orange,
    'inputValidation.errorBorder': p.red,
    'badge.foreground': p.fg,
    'badge.background': p.selection,
    'progressBar.background': p.pink,
    'list.activeSelectionBackground': alpha(p.selection, 0.6),
    'list.activeSelectionForeground': p.fg,
    'list.dropBackground': p.selection,
    'list.focusBackground': p.lineHighlight,
    'list.highlightForeground': p.cyan,
    'list.hoverBackground': alpha(p.selection, 0.65),
    'list.inactiveSelectionBackground': alpha(p.selection, 0.4),
    'list.warningForeground': p.orange,
    'list.errorForeground': p.red,
    'activityBar.background': p.bgLight,
    'activityBar.inactiveForeground': p.comment,
    'activityBar.foreground': p.fg,
    'activityBar.activeBorder': alpha(p.pink, 0.8),
    'activityBar.activeBackground': alpha(p.selection, 0.4),
    'activityBarBadge.background': p.pink,
    'activityBarBadge.foreground': p.bg,
    'sideBar.background': p.bgDark,
    'sideBar.foreground': p.fg,
    'sideBarTitle.foreground': p.fg,
    'sideBarSectionHeader.background': p.bg,
    'sideBarSectionHeader.border': p.bgDarker,
    'editorGroup.border': p.selection,
    'editorGroup.dropBackground': p.tabDrop,
    'editorGroupHeader.tabsBackground': p.bgDarker,
    'tab.activeBackground': p.bg,
    'tab.activeForeground': p.fg,
    'tab.border': p.bgDarker,
    'tab.activeBorderTop': alpha(p.pink, 0.8),
    'tab.inactiveBackground': p.bgDark,
    'tab.inactiveForeground': p.comment,
    'editor.foreground': p.fg,
    'editor.background': p.bg,
    'editorLineNumber.foreground': p.comment,
    'editorCursor.foreground': p.cursor,
    'editor.selectionBackground': p.selection,
    'editor.inactiveSelectionBackground': alpha(p.selection, 0.35),
    'editor.selectionHighlightBackground': p.bgLighter,
    'editor.foldBackground': p.bgDark,
    'editor.wordHighlightBackground': alpha(p.cyan, 0.5),
    'editor.wordHighlightStrongBackground': alpha(p.green, 0.5),
    'editor.findMatchBackground': alpha(p.orange, 0.8),
    'editor.findMatchHighlightBackground': alpha(p.fg, 0.4),
    'editor.findRangeHighlightBackground': p.lineHighlight,
    'editor.hoverHighlightBackground': p.bgDarker,
    'editor.lineHighlightBackground': p.lineHighlight,
    'editor.lineHighlightBorder': p.bg,
    'editorLink.activeForeground': p.cyan,
    'editor.rangeHighlightBackground': alpha(p.purple, 0.15),
    'editor.snippetTabstopHighlightBackground': p.bg,
    'editor.snippetTabstopHighlightBorder': p.comment,
    'editor.snippetFinalTabstopHighlightBackground': p.bg,
    'editor.snippetFinalTabstopHighlightBorder': p.green,
    'editorWhitespace.foreground': p.nonText,
    'editorIndentGuide.background': p.nonText,
    'editorIndentGuide.activeBackground': alpha(p.fg, 0.45),
    'editorRuler.foreground': p.nonText,
    'editorCodeLens.foreground': p.comment,
    'editorInlineSuggest.foreground': alpha(p.fg, 0.55),
    'editorInlineSuggest.background': p.bgDark,
    'editorOverviewRuler.border': p.bgDarker,
    'editorOverviewRuler.selectionHighlightForeground': p.orange,
    'editorOverviewRuler.wordHighlightForeground': p.cyan,
    'editorOverviewRuler.wordHighlightStrongForeground': p.green,
    'editorOverviewRuler.modifiedForeground': alpha(p.cyan, 0.8),
    'editorOverviewRuler.addedForeground': alpha(p.green, 0.8),
    'editorOverviewRuler.deletedForeground': alpha(p.red, 0.8),
    'editorOverviewRuler.errorForeground': alpha(p.red, 0.8),
    'editorOverviewRuler.warningForeground': alpha(p.orange, 0.8),
    'editorOverviewRuler.infoForeground': alpha(p.cyan, 0.8),
    'editorError.foreground': p.red,
    'editorWarning.foreground': p.cyan,
    'editorGutter.modifiedBackground': alpha(p.cyan, 0.8),
    'editorGutter.addedBackground': alpha(p.green, 0.8),
    'editorGutter.deletedBackground': alpha(p.red, 0.8),
    'editorBracketMatch.background': alpha(p.selection, 0.45),
    'editorBracketMatch.border': p.pink,
    'editorBracketHighlight.foreground1': p.pink,
    'editorBracketHighlight.foreground2': p.cyan,
    'editorBracketHighlight.foreground3': p.green,
    'editorBracketHighlight.foreground4': p.yellow,
    'editorBracketHighlight.foreground5': p.orange,
    'editorBracketHighlight.foreground6': p.purple,
    'editorBracketHighlight.unexpectedBracket.foreground': p.red,
    'gitDecoration.modifiedResourceForeground': p.cyan,
    'gitDecoration.deletedResourceForeground': p.red,
    'gitDecoration.untrackedResourceForeground': p.green,
    'gitDecoration.ignoredResourceForeground': p.comment,
    'gitDecoration.conflictingResourceForeground': p.orange,
    'diffEditor.insertedTextBackground': alpha(p.green, 0.2),
    'diffEditor.removedTextBackground': alpha(p.red, 0.5),
    'editorWidget.background': p.bgDark,
    'editorSuggestWidget.background': p.bgDark,
    'editorSuggestWidget.foreground': p.fg,
    'editorSuggestWidget.selectedBackground': p.selection,
    'editorHoverWidget.background': p.bg,
    'editorHoverWidget.border': p.comment,
    'editorMarkerNavigation.background': p.bgDark,
    'peekView.border': p.selection,
    'peekViewEditor.background': p.bg,
    'peekViewEditor.matchHighlightBackground': alpha(p.yellow, 0.8),
    'peekViewResult.background': p.bgDark,
    'peekViewResult.fileForeground': p.fg,
    'peekViewResult.lineForeground': p.fg,
    'peekViewResult.matchHighlightBackground': alpha(p.yellow, 0.8),
    'peekViewResult.selectionBackground': p.selection,
    'peekViewResult.selectionForeground': p.fg,
    'peekViewTitle.background': p.bgDarker,
    'peekViewTitleDescription.foreground': p.comment,
    'peekViewTitleLabel.foreground': p.fg,
    'merge.currentHeaderBackground': alpha(p.green, 0.9),
    'merge.incomingHeaderBackground': alpha(p.purple, 0.9),
    'editorOverviewRuler.currentContentForeground': p.green,
    'editorOverviewRuler.incomingContentForeground': p.purple,
    'panel.background': p.bg,
    'panel.border': p.pink,
    'panelTitle.activeBorder': p.pink,
    'panelTitle.activeForeground': p.fg,
    'panelTitle.inactiveForeground': alpha(p.fg, 0.8),
    'statusBar.background': p.bgDarker,
    'statusBar.foreground': p.fg,
    'statusBar.debuggingBackground': p.red,
    'statusBar.debuggingForeground': p.bgDarker,
    'statusBar.noFolderBackground': p.bgDarker,
    'statusBar.noFolderForeground': p.fg,
    'statusBarItem.prominentBackground': p.red,
    'statusBarItem.prominentHoverBackground': p.orange,
    'statusBarItem.remoteForeground': p.fg,
    'statusBarItem.remoteBackground': p.purple,
    'titleBar.activeBackground': p.bgDark,
    'titleBar.activeForeground': p.fg,
    'titleBar.inactiveBackground': p.bgDarker,
    'titleBar.inactiveForeground': p.comment,
    'notification.background': p.bg,
    'notification.foreground': p.fg,
    'notification.buttonBackground': p.selection,
    'notification.buttonForeground': p.fg,
    'notification.buttonHoverBackground': p.lineHighlight,
    'notification.errorBackground': p.red,
    'notification.errorForeground': p.fg,
    'notification.infoBackground': p.cyan,
    'notification.infoForeground': p.bg,
    'notification.warningBackground': p.orange,
    'notification.warningForeground': p.bg,
    'extensionButton.prominentForeground': p.fg,
    'extensionButton.prominentBackground': alpha(p.green, 0.9),
    'extensionButton.prominentHoverBackground': alpha(p.green, 0.6),
    'pickerGroup.border': p.purple,
    'pickerGroup.foreground': p.cyan,
    'debugToolBar.background': p.bgDark,
    'walkThrough.embeddedEditorBackground': p.bgDark,
    'settings.headerForeground': p.fg,
    'settings.modifiedItemForeground': p.orange,
    'settings.modifiedItemIndicator': p.orange,
    'settings.dropdownBackground': p.bgDark,
    'settings.dropdownForeground': p.fg,
    'settings.dropdownBorder': p.bgDarker,
    'settings.checkboxBackground': p.bgDark,
    'settings.checkboxForeground': p.fg,
    'settings.checkboxBorder': p.bgDarker,
    'settings.textInputBackground': p.bgDark,
    'settings.textInputForeground': p.fg,
    'settings.textInputBorder': p.bgDarker,
    'settings.numberInputBackground': p.bgDark,
    'settings.numberInputForeground': p.fg,
    'settings.numberInputBorder': p.bgDarker,
    'breadcrumb.foreground': p.comment,
    'breadcrumb.background': p.bg,
    'breadcrumb.focusForeground': p.fg,
    'breadcrumb.activeSelectionForeground': p.fg,
    'breadcrumbPicker.background': p.bgDarker,
    'listFilterWidget.background': p.bgLight,
    'listFilterWidget.outline': p.bgLighter,
    'listFilterWidget.noMatchesOutline': p.red,
  };
}

function buildSemanticTokenColors(p) {
  return {
    newOperator: { foreground: p.pink, fontStyle: 'bold' },
    string: { foreground: p.yellow },
    number: { foreground: p.orange },
    comment: { foreground: p.comment },
    keyword: { foreground: p.pink },
    'keyword.control': { foreground: p.pink },
    function: { foreground: p.green },
    method: { foreground: p.green },
    class: { foreground: p.cyan, fontStyle: 'normal' },
    interface: { foreground: p.cyan, fontStyle: 'italic' },
    enum: { foreground: p.cyan, fontStyle: 'italic' },
    type: { foreground: p.cyan, fontStyle: 'italic' },
    typeParameter: { foreground: p.orange },
    parameter: { foreground: p.orange, fontStyle: 'italic' },
    property: { foreground: p.fg },
    variable: { foreground: p.fg },
    namespace: { foreground: p.purple },
    enumMember: { foreground: p.purple },
    decorator: { foreground: p.green, fontStyle: 'italic' },
    macro: { foreground: p.green },
    struct: { foreground: p.cyan },
    modifier: { foreground: p.pink },
    operator: { foreground: p.pink },
    regexp: { foreground: p.yellow },
    boolean: { foreground: p.purple, fontStyle: 'italic' },
  };
}

function buildTokenColors(p) {
  return [
    { scope: ['emphasis'], settings: { fontStyle: 'italic' } },
    { scope: ['strong'], settings: { fontStyle: 'bold' } },
    { scope: ['header'], settings: { foreground: p.purple } },
    { scope: ['source'], settings: { foreground: p.fg } },
    { scope: ['meta.diff', 'meta.diff.header'], settings: { foreground: p.comment } },
    { scope: ['markup.inserted'], settings: { foreground: p.green } },
    { scope: ['markup.deleted'], settings: { foreground: p.red } },
    { scope: ['markup.changed'], settings: { foreground: p.orange } },
    { scope: ['invalid'], settings: { foreground: p.red, fontStyle: 'underline italic' } },
    { scope: ['invalid.deprecated'], settings: { foreground: p.fg, fontStyle: 'underline italic' } },
    { scope: ['entity.name.filename'], settings: { foreground: p.yellow } },
    { scope: ['markup.error'], settings: { foreground: p.red } },
    { name: 'Underlined markup', scope: ['markup.underline'], settings: { fontStyle: 'underline' } },
    { name: 'Bold markup', scope: ['markup.bold'], settings: { fontStyle: 'bold', foreground: p.orange } },
    { name: 'Markup headings', scope: ['markup.heading'], settings: { fontStyle: 'bold', foreground: p.purple } },
    { name: 'Markup italic', scope: ['markup.italic'], settings: { foreground: p.yellow, fontStyle: 'italic' } },
    {
      name: 'Bullets, lists (prose)',
      scope: [
        'beginning.punctuation.definition.list.markdown',
        'beginning.punctuation.definition.quote.markdown',
        'punctuation.definition.link.restructuredtext',
      ],
      settings: { foreground: p.cyan },
    },
    {
      name: 'Inline code (prose)',
      scope: ['markup.inline.raw', 'markup.raw.restructuredtext'],
      settings: { foreground: p.green },
    },
    {
      name: 'Links (prose)',
      scope: ['markup.underline.link', 'markup.underline.link.image'],
      settings: { foreground: p.cyan },
    },
    {
      name: 'Link text, image alt text (prose)',
      scope: [
        'meta.link.reference.def.restructuredtext',
        'punctuation.definition.directive.restructuredtext',
        'string.other.link.description',
        'string.other.link.title',
      ],
      settings: { foreground: p.pink },
    },
    {
      name: 'Blockquotes (prose)',
      scope: ['entity.name.directive.restructuredtext', 'markup.quote'],
      settings: { foreground: p.yellow, fontStyle: 'italic' },
    },
    { name: 'Horizontal rule (prose)', scope: ['meta.separator.markdown'], settings: { foreground: p.comment } },
    {
      name: 'Code blocks',
      scope: [
        'fenced_code.block.language',
        'markup.raw.inner.restructuredtext',
        'markup.fenced_code.block.markdown punctuation.definition.markdown',
      ],
      settings: { foreground: p.green },
    },
    {
      name: 'Prose constants',
      scope: ['punctuation.definition.constant.restructuredtext'],
      settings: { foreground: p.purple },
    },
    {
      name: 'Braces in markdown headings',
      scope: [
        'markup.heading.markdown punctuation.definition.string.begin',
        'markup.heading.markdown punctuation.definition.string.end',
      ],
      settings: { foreground: p.purple },
    },
    {
      name: 'Braces in markdown paragraphs',
      scope: [
        'meta.paragraph.markdown punctuation.definition.string.begin',
        'meta.paragraph.markdown punctuation.definition.string.end',
      ],
      settings: { foreground: p.fg },
    },
    {
      name: 'Braces in markdown blockquotes',
      scope: [
        'markup.quote.markdown meta.paragraph.markdown punctuation.definition.string.begin',
        'markup.quote.markdown meta.paragraph.markdown punctuation.definition.string.end',
      ],
      settings: { foreground: p.yellow },
    },
    {
      name: 'User-defined class names',
      scope: ['entity.name.type.class', 'entity.name.class'],
      settings: { foreground: p.cyan, fontStyle: 'normal' },
    },
    {
      name: 'this, super, self, etc.',
      scope: [
        'keyword.expressions-and-types.swift',
        'keyword.other.this',
        'variable.language',
        'variable.language punctuation.definition.variable.php',
        'variable.other.readwrite.instance.ruby',
        'variable.parameter.function.language.special',
      ],
      settings: { foreground: p.purple, fontStyle: 'italic' },
    },
    {
      name: 'Inherited classes',
      scope: ['entity.other.inherited-class'],
      settings: { fontStyle: 'italic', foreground: p.cyan },
    },
    {
      name: 'Comments',
      scope: ['comment', 'punctuation.definition.comment', 'unused.comment', 'wildcard.comment'],
      settings: { foreground: p.comment },
    },
    {
      name: 'JSDoc-style keywords',
      scope: [
        'comment keyword.codetag.notation',
        'comment.block.documentation keyword',
        'comment.block.documentation storage.type.class',
      ],
      settings: { foreground: p.pink },
    },
    {
      name: 'JSDoc-style types',
      scope: ['comment.block.documentation entity.name.type'],
      settings: { foreground: p.cyan, fontStyle: 'italic' },
    },
    {
      name: 'JSDoc-style type brackets',
      scope: ['comment.block.documentation entity.name.type punctuation.definition.bracket'],
      settings: { foreground: p.cyan },
    },
    {
      name: 'JSDoc-style comment parameters',
      scope: ['comment.block.documentation variable'],
      settings: { foreground: p.orange, fontStyle: 'italic' },
    },
    {
      name: 'Constants',
      scope: ['constant', 'variable.other.constant'],
      settings: { foreground: p.purple },
    },
    {
      name: 'Constant escape sequences',
      scope: ['constant.character.escape', 'constant.character.string.escape', 'constant.regexp'],
      settings: { foreground: p.pink },
    },
    { name: 'HTML tags', scope: ['entity.name.tag'], settings: { foreground: p.pink } },
    {
      name: 'CSS attribute parent selectors',
      scope: ['entity.other.attribute-name.parent-selector'],
      settings: { foreground: p.pink },
    },
    {
      name: 'CSS ID',
      scope: ['entity.other.attribute-name.id'],
      settings: { foreground: p.yellow, fontStyle: 'italic' },
    },
    {
      name: 'HTML/CSS attribute names',
      scope: ['entity.other.attribute-name'],
      settings: { foreground: p.green, fontStyle: 'italic' },
    },
    { name: 'Tag inline source', scope: ['meta.tag.inline source'], settings: { foreground: p.yellow } },
    {
      name: 'Function names',
      scope: [
        'entity.name.function',
        'meta.function-call.generic',
        'meta.function-call.object',
        'meta.function-call.php',
        'meta.function-call.static',
        'meta.method-call.java meta.method',
        'meta.method.groovy',
        'support.function.any-method.lua',
        'keyword.operator.function.infix',
      ],
      settings: { foreground: p.green },
    },
    {
      name: 'Function parameters',
      scope: [
        'entity.name.variable.parameter',
        'meta.at-rule.function variable',
        'meta.at-rule.mixin variable',
        'meta.function.arguments variable.other.php',
        'meta.selectionset.graphql meta.arguments.graphql variable.arguments.graphql',
        'variable.parameter',
      ],
      settings: { fontStyle: 'italic', foreground: p.orange },
    },
    {
      name: 'Decorators',
      scope: ['meta.decorator variable.other.readwrite', 'meta.decorator variable.other.property'],
      settings: { foreground: p.green, fontStyle: 'italic' },
    },
    {
      name: 'Decorator Objects',
      scope: ['meta.decorator variable.other.object'],
      settings: { foreground: p.green },
    },
    {
      name: 'Keywords',
      scope: ['keyword', 'punctuation.definition.keyword'],
      settings: { foreground: p.pink },
    },
    {
      name: 'Keyword "new"',
      scope: ['keyword.control.new', 'keyword.operator.new'],
      settings: { fontStyle: 'bold' },
    },
    { name: 'Generic selectors (CSS)', scope: ['meta.selector'], settings: { foreground: p.pink } },
    {
      name: 'Language Built-ins',
      scope: ['support'],
      settings: { fontStyle: 'italic', foreground: p.cyan },
    },
    {
      name: 'Built-in magic functions and constants',
      scope: ['support.function.magic', 'support.variable', 'variable.other.predefined'],
      settings: { fontStyle: 'regular', foreground: p.purple },
    },
    {
      name: 'Built-in functions / properties',
      scope: ['support.function', 'support.type.property-name'],
      settings: { fontStyle: 'regular' },
    },
    {
      name: 'Separators',
      scope: [
        'constant.other.symbol.hashkey punctuation.definition.constant.ruby',
        'entity.other.attribute-name.placeholder punctuation',
        'entity.other.attribute-name.pseudo-class punctuation',
        'entity.other.attribute-name.pseudo-element punctuation',
        'meta.group.double.toml',
        'meta.group.toml',
        'meta.object-binding-pattern-variable punctuation.destructuring',
        'punctuation.colon.graphql',
        'punctuation.definition.block.scalar.folded.yaml',
        'punctuation.definition.block.scalar.literal.yaml',
        'punctuation.definition.block.sequence.item.yaml',
        'punctuation.definition.entity.other.inherited-class',
        'punctuation.function.swift',
        'punctuation.separator.dictionary.key-value',
        'punctuation.separator.hash',
        'punctuation.separator.inheritance',
        'punctuation.separator.key-value',
        'punctuation.separator.key-value.mapping.yaml',
        'punctuation.separator.namespace',
        'punctuation.separator.pointer-access',
        'punctuation.separator.slice',
        'string.unquoted.heredoc punctuation.definition.string',
        'support.other.chomping-indicator.yaml',
        'punctuation.separator.annotation',
      ],
      settings: { foreground: p.pink },
    },
    {
      name: 'Brackets, braces, parens',
      scope: [
        'keyword.operator.other.powershell',
        'keyword.other.statement-separator.powershell',
        'meta.brace.round',
        'meta.function-call punctuation',
        'punctuation.definition.arguments.begin',
        'punctuation.definition.arguments.end',
        'punctuation.definition.entity.begin',
        'punctuation.definition.entity.end',
        'punctuation.definition.tag.cs',
        'punctuation.definition.type.begin',
        'punctuation.definition.type.end',
        'punctuation.section.scope.begin',
        'punctuation.section.scope.end',
        'storage.type.generic.java',
        'string.template meta.brace',
        'string.template punctuation.accessor',
      ],
      settings: { foreground: p.fg },
    },
    {
      name: 'Variable interpolation operators',
      scope: [
        'meta.string-contents.quoted.double punctuation.definition.variable',
        'punctuation.definition.interpolation.begin',
        'punctuation.definition.interpolation.end',
        'punctuation.definition.template-expression.begin',
        'punctuation.definition.template-expression.end',
        'punctuation.section.embedded.begin',
        'punctuation.section.embedded.coffee',
        'punctuation.section.embedded.end',
        'punctuation.section.embedded.end source.php',
        'punctuation.section.embedded.end source.ruby',
        'punctuation.definition.variable.makefile',
      ],
      settings: { foreground: p.pink },
    },
    {
      name: 'Keys (serializable languages)',
      scope: [
        'entity.name.function.target.makefile',
        'entity.name.section.toml',
        'entity.name.tag.yaml',
        'variable.other.key.toml',
      ],
      settings: { foreground: p.cyan },
    },
    {
      name: 'Dates / timestamps',
      scope: ['constant.other.date', 'constant.other.timestamp'],
      settings: { foreground: p.orange },
    },
    {
      name: 'YAML aliases',
      scope: ['variable.other.alias.yaml'],
      settings: { fontStyle: 'italic underline', foreground: p.green },
    },
    {
      name: 'Storage',
      scope: [
        'storage',
        'meta.implementation storage.type.objc',
        'meta.interface-or-protocol storage.type.objc',
        'source.groovy storage.type.def',
      ],
      settings: { fontStyle: 'regular', foreground: p.pink },
    },
    {
      name: 'Types',
      scope: [
        'entity.name.type',
        'keyword.primitive-datatypes.swift',
        'keyword.type.cs',
        'meta.protocol-list.objc',
        'meta.return-type.objc',
        'source.go storage.type',
        'source.groovy storage.type',
        'source.java storage.type',
        'source.powershell entity.other.attribute-name',
        'storage.class.std.rust',
        'storage.type.attribute.swift',
        'storage.type.c',
        'storage.type.core.rust',
        'storage.type.cs',
        'storage.type.groovy',
        'storage.type.objc',
        'storage.type.php',
        'storage.type.haskell',
        'storage.type.ocaml',
      ],
      settings: { fontStyle: 'italic', foreground: p.cyan },
    },
    {
      name: 'Generics and mapped types',
      scope: [
        'entity.name.type.type-parameter',
        'meta.indexer.mappedtype.declaration entity.name.type',
        'meta.type.parameters entity.name.type',
      ],
      settings: { foreground: p.orange },
    },
    { name: 'Modifiers', scope: ['storage.modifier'], settings: { foreground: p.pink } },
    {
      name: 'RegExp string',
      scope: [
        'string.regexp',
        'constant.other.character-class.set.regexp',
        'constant.character.escape.backslash.regexp',
      ],
      settings: { foreground: p.yellow },
    },
    {
      name: 'Non-capture operators',
      scope: ['punctuation.definition.group.capture.regexp'],
      settings: { foreground: p.pink },
    },
    {
      name: 'RegExp start and end characters',
      scope: ['string.regexp punctuation.definition.string.begin', 'string.regexp punctuation.definition.string.end'],
      settings: { foreground: p.red },
    },
    {
      name: 'Character group',
      scope: ['punctuation.definition.character-class.regexp'],
      settings: { foreground: p.cyan },
    },
    {
      name: 'Capture groups',
      scope: ['punctuation.definition.group.regexp'],
      settings: { foreground: p.orange },
    },
    {
      name: 'Assertion operators',
      scope: ['punctuation.definition.group.assertion.regexp', 'keyword.operator.negation.regexp'],
      settings: { foreground: p.red },
    },
    {
      name: 'Positive lookaheads',
      scope: ['meta.assertion.look-ahead.regexp'],
      settings: { foreground: p.green },
    },
    { name: 'Strings', scope: ['string'], settings: { foreground: p.yellow } },
    {
      name: 'String quotes',
      scope: ['punctuation.definition.string.begin', 'punctuation.definition.string.end'],
      settings: { foreground: p.tempQuotes },
    },
    {
      name: 'Property quotes',
      scope: ['punctuation.support.type.property-name.begin', 'punctuation.support.type.property-name.end'],
      settings: { foreground: p.tempPropertyQuotes },
    },
    {
      name: 'Docstrings',
      scope: [
        'string.quoted.docstring.multi',
        'string.quoted.docstring.multi.python punctuation.definition.string.begin',
        'string.quoted.docstring.multi.python punctuation.definition.string.end',
        'string.quoted.docstring.multi.python constant.character.escape',
      ],
      settings: { foreground: p.comment },
    },
    {
      name: 'Variables and object properties',
      scope: [
        'variable',
        'constant.other.key.perl',
        'support.variable.property',
        'variable.other.constant.js',
        'variable.other.constant.ts',
        'variable.other.constant.tsx',
      ],
      settings: { foreground: p.fg },
    },
    {
      name: 'Destructuring / aliasing reference name (LHS)',
      scope: [
        'meta.import variable.other.readwrite',
        'meta.object-binding-pattern-variable variable.object.property',
        'meta.variable.assignment.destructured.object.coffee variable',
      ],
      settings: { fontStyle: 'italic', foreground: p.orange },
    },
    {
      name: 'Destructuring / aliasing variable name (RHS)',
      scope: [
        'meta.import variable.other.readwrite.alias',
        'meta.export variable.other.readwrite.alias',
        'meta.variable.assignment.destructured.object.coffee variable variable',
      ],
      settings: { fontStyle: 'normal', foreground: p.fg },
    },
    {
      name: 'GraphQL keys',
      scope: ['meta.selectionset.graphql variable'],
      settings: { foreground: p.yellow },
    },
    {
      name: 'GraphQL function arguments',
      scope: ['meta.selectionset.graphql meta.arguments variable'],
      settings: { foreground: p.fg },
    },
    {
      name: 'GraphQL fragment name',
      scope: ['entity.name.fragment.graphql', 'variable.fragment.graphql'],
      settings: { foreground: p.cyan },
    },
    {
      name: 'Edge cases',
      scope: [
        'constant.other.symbol.hashkey.ruby',
        'keyword.operator.dereference.java',
        'keyword.operator.navigation.groovy',
        'meta.scope.for-loop.shell punctuation.definition.string.begin',
        'meta.scope.for-loop.shell punctuation.definition.string.end',
        'meta.scope.for-loop.shell string',
        'storage.modifier.import',
        'punctuation.section.embedded.begin.tsx',
        'punctuation.section.embedded.end.tsx',
        'punctuation.section.embedded.begin.jsx',
        'punctuation.section.embedded.end.jsx',
        'punctuation.section.embedded.begin.html',
        'punctuation.section.embedded.end.html',
      ],
      settings: { foreground: p.pink },
    },
    {
      name: 'C# Razor / ASP.NET',
      scope: [
        'meta.embedded.line.cshtml',
        'source.cs meta.embedded.line',
        'string.quoted.double.cshtml',
        'entity.name.tag.cshtml',
      ],
      settings: { foreground: p.cyan },
    },
    {
      name: 'SQL keywords',
      scope: [
        'keyword.other.DML.sql',
        'keyword.other.DDL.create.II.sql',
        'keyword.other.DDL.create.sql',
        'keyword.other.DDL.sql',
        'keyword.other.sql',
      ],
      settings: { foreground: p.pink },
    },
    {
      name: 'SQL functions',
      scope: ['support.function.sql', 'support.type.sql'],
      settings: { foreground: p.cyan, fontStyle: 'italic' },
    },
    {
      name: 'SQL strings',
      scope: ['string.quoted.single.sql', 'string.quoted.double.sql'],
      settings: { foreground: p.yellow },
    },
    {
      name: 'JSON property names',
      scope: ['support.type.property-name.json'],
      settings: { foreground: p.cyan },
    },
    {
      name: 'JSON values',
      scope: ['constant.numeric.json', 'constant.language.json'],
      settings: { foreground: p.orange },
    },
    {
      name: 'TypeScript/JavaScript types',
      scope: [
        'entity.name.type.interface',
        'entity.name.type.alias',
        'support.type.builtin.ts',
        'support.type.primitive.ts',
        'support.type.builtin.tsx',
        'support.type.primitive.tsx',
      ],
      settings: { foreground: p.cyan, fontStyle: 'italic' },
    },
    {
      name: 'Namespaces',
      scope: ['entity.name.namespace', 'entity.name.scope-resolution'],
      settings: { foreground: p.purple },
    },
    {
      name: 'Operators',
      scope: ['keyword.operator', 'keyword.operator.arithmetic', 'keyword.operator.logical'],
      settings: { foreground: p.pink },
    },
    {
      name: 'Booleans',
      scope: ['constant.language.boolean', 'constant.language.null', 'constant.language.undefined'],
      settings: { foreground: p.purple, fontStyle: 'italic' },
    },
    {
      name: 'Numbers',
      scope: ['constant.numeric', 'constant.numeric.integer', 'constant.numeric.float'],
      settings: { foreground: p.orange },
    },
    {
      name: 'CSS properties',
      scope: ['support.type.property-name.css', 'meta.property-name.css'],
      settings: { foreground: p.cyan },
    },
    {
      name: 'CSS values',
      scope: ['support.constant.property-value.css', 'constant.other.color.rgb-value.css'],
      settings: { foreground: p.yellow },
    },
  ];
}

const themeFiles = {
  light: 'nebula-aura-light-color-theme.json',
  dark: 'nebula-aura-dark-color-theme.json',
  violet: 'nebula-aura-violet-color-theme.json',
  midnight: 'nebula-aura-midnight-color-theme.json',
};

if (!fs.existsSync(themesDir)) {
  fs.mkdirSync(themesDir, { recursive: true });
}

for (const [key, filename] of Object.entries(themeFiles)) {
  const palette = palettes[key];
  const theme = {
    name: palette.name,
    type: palette.type,
    colors: buildColors(palette),
    tokenColors: buildTokenColors(palette),
  };

  if (palette.semanticHighlighting) {
    theme.semanticHighlighting = true;
    theme.semanticTokenColors = buildSemanticTokenColors(palette);
  }

  fs.writeFileSync(path.join(themesDir, filename), `${JSON.stringify(theme)}\n`);
  console.log(`Generated ${filename}`);
}
